name: Docker Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to docker
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        PM2_PUBLIC_KEY: ${{ secrets.PM2_PUBLIC_KEY }}
        PM2_SECRET_KEY: ${{ secrets.PM2_SECRET_KEY }}
        PM2_MACHINE_NAME: ${{ secrets.PM2_MACHINE_NAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build docker image
      run: docker build -t $DOCKER_USERNAME/betakopa-main --build-arg PM2_PUBLIC_KEY=$PM2_PUBLIC_KEY --build-arg PM2_SECRET_KEY=PM2_SECRET_KEY --build-arg PM2_MACHINE_NAME=$PM2_MACHINE_NAME .
    - name: Push to docker
      run: docker push $DOCKER_USERNAME/betakopa-main:latest